### ISSUE TITLE
Documentation edit

### ISSUE THREAD

**Issue by julietshen** [Jigsaw-Code/altitude#4]
Hello! Thanks for this project! I noticed that the setup instructions reference cloning the `platform-defender` repo, which doesn't match the Altitude name. I got it running by manually cloning the repo, but if this is not intentional I'm happy to submit a PR to update the documentation.

**Comment by sbruens** [comment]
Thank you for reporting this @julietshen! Fixed by https://github.com/Jigsaw-Code/altitude/commit/9e0d979b4e1815ec9c4e8446650a25a67778caa8.
